-- 코드를 입력하세요
-- 일단 PRODUCT_CODE를 앞 두자리로 자르고
-- GROUP BY 하고 카운트
SELECT PRODUCT_CODE CATEGORY, COUNT(PRODUCT_CODE) 
FROM (SELECT SUBSTR(PRODUCT_CODE , 1, 2) PRODUCT_CODE FROM PRODUCT)
GROUP BY PRODUCT_CODE
ORDER BY CATEGORY