-- 코드를 입력하세요
-- DATETIME을 HOUR로 바꾸기
-- HOUR GROUP BY COUNT 하기
-- SELECT HOUR(DATETIME) DATETIME	 FROM ANIMAL_OUTS
SELECT HOUR, COUNT(HOUR) C
FROM (SELECT HOUR(DATETIME) HOUR FROM ANIMAL_OUTS) A
WHERE HOUR > 8 AND HOUR < 20
GROUP BY HOUR
ORDER BY HOUR