-- 코드를 입력하세요
SELECT ROUND(AVG(DAILY_FEE)) AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'
GROUP BY CAR_TYPE


--SELECT DAILY_FEE,CAR_TYPE
--FROM CAR_RENTAL_COMPANY_CAR
--WHERE CAR_TYPE = 'SUV'
--GROUP BY CAR_TYPE